# Enables or disables the plugin entirely.
# If set to false, the plugin will not register any listeners or send messages.
enabled: true

# This contains all configurable messages handled by the plugin,
# such as join, quit, death, and system messages.
messages:

  # These messages are default for everyone unless overridden
  # by a group-based or player-specific message.
  default:

    # Random message from this list will be sent when a player joins the server.
    # Multiple messages are okay to add here.
    # Available built-in placeholders (no PlaceholderAPI needed): %player_name%, %player_username%
    join:
      - "%player_display_name% joined the server"
      - "%player_display_name% is now online"

    # Random message from this list will be sent when a player quits the server.
    # Multiple messages are okay to add here.
    # Available built-in placeholders (no PlaceholderAPI needed): %player_name%, %player_username%
    quit:
      - "%player_display_name% left the server"
      - "%player_display_name% went offline"

  # System messages used internally by the plugin.
  # These messages are shown in the console or as command feedback,
  # and are not related to gameplay events.
  system:

    # Plugin lifecycle messages.
    lifecycle:

      # Message sent to the console when the plugin is enabled.
      enable: "Enabled Letters v%plugin_version%"

      # Message sent to the console when the plugin is disabling.
      disable: "Disabled Letters v%plugin_version%"

    # Messages related to plugin and config checks
    checks:

      # Message sent to the console when the plugin is disabled.
      plugin-disabled: "Plugin is disabled in config."

    # Command-related system messages.
    commands:

      # Message sent when the plugin is reloaded.
      reload: "Reloaded Letters v%plugin_version%"

      # Message sent when no subcommand is used.
      no-command: "You must specify a subcommand."

      # Message sent when the player lacks permission.
      no-permission: "You do not have permission to do that."

      # Message sent when an invalid subcommand is used.
      invalid-command: "Unknown command."